[package]
name = "eve"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.0", features = ["derive"] }
curl = "0.4.44"
regex = "1.10.2"
serde_json = "1.0"
termion = "2.0.1"
textwrap = "0.12.1"

[dev-dependencies]
tempfile = "3.8.1"